version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: reguser
      POSTGRES_PASSWORD: regpass
      POSTGRES_DB: registrationdb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: reguser
      DB_PASSWORD: regpass
      DB_NAME: registrationdb
      DB_PORT: 5432
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
