version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${ECR_REGISTRY}/registration-app-backend:${TAG:-latest}
    container_name: registration-app_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/registration
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${ECR_REGISTRY}/registration-app-frontend:${TAG:-latest}
    container_name: registration-app_frontend
    restart: always
    ports:
      - "3000:3000"

  db:
    image: postgres:15
    container_name: registration-app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: registration
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:


