name: CI/CD Full Deployment (No SSL)

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 503640389215.dkr.ecr.us-east-1.amazonaws.com
  APP_EC2_IP: ${{ secrets.APP_EC2_IP }}
  PROXY_EC2_IP: ${{ secrets.PROXY_EC2_IP }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push backend
        run: |
          docker build -t registration-app-backend:latest ./backend
          docker tag registration-app-backend:latest $ECR_REGISTRY/registration-app-backend:latest
          docker push $ECR_REGISTRY/registration-app-backend:latest

      - name: Build & push frontend
        run: |
          docker build -t registration-app-frontend:latest ./frontend
          docker tag registration-app-frontend:latest $ECR_REGISTRY/registration-app-frontend:latest
          docker push $ECR_REGISTRY/registration-app-frontend:latest

  deploy-app-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on App EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.APP_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.APP_EC2_SSH_KEY }}
          script: |
            echo "Updating app repo..."
            cd ~/registration-app || exit
            git reset --hard
            git pull

            echo "Logging in to AWS ECR..."
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_DEFAULT_REGION=us-east-1
            aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

            echo "Starting containers..."
            docker-compose -f docker-compose.ecr.yml pull
            docker-compose -f docker-compose.ecr.yml up -d --remove-orphans

  deploy-proxy-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy proxy (no SSL)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROXY_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.PROXY_EC2_SSH_KEY }}
          script: |
            echo "Deploying Nginx proxy..."
            cd ~/registration-app/Proxy || exit
            docker-compose -f docker-compose.yml up -d --build --remove-orphans

























         



