name: Deploy Registration App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
  APP_DIR: ~/app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials for ECR login
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 3: Login to Amazon ECR
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Step 4: Build & push frontend Docker image
      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ env.ECR_REGISTRY }}/registration-frontend:latest
          build-args: |
            REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}

      # Step 5: Build & push backend Docker image
      - name: Build & Push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ env.ECR_REGISTRY }}/registration-backend:latest

      # Step 6: Copy docker-compose file to EC2 App server
      - name: Copy docker-compose file to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: docker-compose.app.yml
          target: ${{ env.APP_DIR }}

      # Step 7: Deploy to EC2 App server via SSH
      - name: Deploy App on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            mkdir -p ${{ env.APP_DIR }}
            cd ${{ env.APP_DIR }}

            # Update system and install dependencies
            sudo apt update -y
            sudo apt install -y docker.io unzip curl python3-pip

            # Install docker-compose plugin if missing
            if ! command -v docker-compose &> /dev/null; then
              sudo apt install -y docker-compose-plugin
            fi

            # Install AWS CLI v2 if missing
            if ! command -v aws &> /dev/null; then
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install --update
            fi

            # Login Docker to ECR
            aws ecr get-login-password --region $AWS_REGION | sudo docker login --username AWS --password-stdin $ECR_REGISTRY

            # Pull latest images and start containers
            sudo docker compose -f docker-compose.app.yml pull
            sudo docker compose -f docker-compose.app.yml up -d --remove-orphans
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
          APP_DIR: ${{ env.APP_DIR }}













         



